/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package client.transportunit;

import application.transportunit.TransportUnitApplication;
import application.transportunittype.TransportUnitTypeApplication;
import entity.UnidadTransporte;
import javax.swing.JOptionPane;
import util.EntityType;
import util.InstanceFactory;
import util.Strings;

/**
 *
 * @author LUIS
 */
public class NewTransportUnitView extends javax.swing.JDialog {
    
    TransportUnitApplication transportUnitApplication = InstanceFactory.Instance.getInstance("transportUnitApplication", TransportUnitApplication.class);
    TransportUnitTypeApplication transportUnitTypeApplication = InstanceFactory.Instance.getInstance("transportUnitTypeApplication", TransportUnitTypeApplication.class);
    UnidadTransporte updatedTransportUnit;
    String eventType = "CREATE";
    
    /**
     * Creates new form NewTU
     * @param parent
     * @param modal
     */
    public NewTransportUnitView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setupElements();
    }
    
    public NewTransportUnitView(java.awt.Frame parent, boolean modal, UnidadTransporte transportUnit) {
        super(parent, modal);
        initComponents();
        updatedTransportUnit = transportUnit;
        eventType = "UPDATE";
        setupElements();
        fillTransportUnitData(updatedTransportUnit);
    }
    
    public final void setupElements(){
        fillCombos();
    }
    
    public void fillTransportUnitData(UnidadTransporte transportUnit){
        plateTxt.setText(transportUnit.getPlaca());
        transportistTxt.setText(transportUnit.getTransportista());
        typeCombo.setSelectedItem(transportUnit.getTipoUnidadTransporte().getDescripcion());
    }
    
    public void fillCombos(){
        EntityType.TRANSPORT_TYPES = transportUnitTypeApplication.getAllTransportUnitTypes();
        EntityType.fillUnitTransportTypesNames();
        typeCombo.setModel(new javax.swing.DefaultComboBoxModel(EntityType.TRANSPORT_TYPE_NAMES));
    }
    
    public void clearFields(){
        plateTxt.setText("");
        transportistTxt.setText("");
    }

    private Boolean createAndSaveTransportUnit() {
        UnidadTransporte transportUnit = new UnidadTransporte();
        transportUnit.setPlaca(plateTxt.getText());
        transportUnit.setTransportista(transportistTxt.getText());
        transportUnit.setEstado(1);
        transportUnit.setTipoUnidadTransporte(EntityType.TRANSPORT_TYPES.get(typeCombo.getSelectedIndex()-1));
        return transportUnitApplication.createTransportUnit(transportUnit);    
    }

    private Boolean saveTransportUnit() {
        updatedTransportUnit.setPlaca(plateTxt.getText());
        updatedTransportUnit.setTransportista(transportistTxt.getText());
        updatedTransportUnit.setEstado(1);
        updatedTransportUnit.setTipoUnidadTransporte(EntityType.TRANSPORT_TYPES.get(typeCombo.getSelectedIndex()-1));
        return transportUnitApplication.updateTransportUnit(updatedTransportUnit);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plateTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        typeCombo = new javax.swing.JComboBox();
        saveTxt = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        transportistTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Placa:");

        jLabel3.setText("TIpo:");

        typeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        typeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeComboActionPerformed(evt);
            }
        });

        saveTxt.setText("Guardar");
        saveTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveTxtActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancelar");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Transportista:");

        transportistTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transportistTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(typeCombo, 0, 235, Short.MAX_VALUE)
                                    .addComponent(plateTxt)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(transportistTxt))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveTxt)))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(plateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(transportistTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(typeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(saveTxt))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveTxtActionPerformed
        // TODO add your handling code here:
        Boolean response = eventType.equals("CREATE") ? createAndSaveTransportUnit() : saveTransportUnit();
        if (response){
            JOptionPane.showMessageDialog(this, Strings.MESSAGE_NEW_TRANSPORT_UNIT_CREATED,Strings.MESSAGE_TRANSPORT_UNIT_TITLE,JOptionPane.INFORMATION_MESSAGE);
            if(eventType.equals("CREATE")){
                clearFields();               
            }
        }
        else
            JOptionPane.showMessageDialog(this, Strings.ERROR_MESSAGE_TRANSPORT_UNIT,Strings.MESSAGE_TRANSPORT_UNIT_TITLE,JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_saveTxtActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void typeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeComboActionPerformed

    private void transportistTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transportistTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transportistTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField plateTxt;
    private javax.swing.JButton saveTxt;
    private javax.swing.JTextField transportistTxt;
    private javax.swing.JComboBox typeCombo;
    // End of variables declaration//GEN-END:variables

}
