package Domain;
// Generated 04/04/2015 02:29:48 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Accion generated by hbm2java
 */
public class Accion  implements java.io.Serializable {


     private int idAccion;
     private String nombre;
     private Integer idPadre;
     private Set perfils = new HashSet(0);

    public Accion() {
    }

	
    public Accion(int idAccion) {
        this.idAccion = idAccion;
    }
    public Accion(int idAccion, String nombre, Integer idPadre, Set perfils) {
       this.idAccion = idAccion;
       this.nombre = nombre;
       this.idPadre = idPadre;
       this.perfils = perfils;
    }
   
    public int getIdAccion() {
        return this.idAccion;
    }
    
    public void setIdAccion(int idAccion) {
        this.idAccion = idAccion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getIdPadre() {
        return this.idPadre;
    }
    
    public void setIdPadre(Integer idPadre) {
        this.idPadre = idPadre;
    }
    public Set getPerfils() {
        return this.perfils;
    }
    
    public void setPerfils(Set perfils) {
        this.perfils = perfils;
    }




}


