package entity;
// Generated 13/06/2015 10:34:15 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Accion generated by hbm2java
 */
public class Accion  implements java.io.Serializable {


     private Integer id;
     private Accion accion;
     private String nombre;
     private Set perfils = new HashSet(0);
     private Set accions = new HashSet(0);

    public Accion() {
    }

    public Accion(Accion accion, String nombre, Set perfils, Set accions) {
       this.accion = accion;
       this.nombre = nombre;
       this.perfils = perfils;
       this.accions = accions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Accion getAccion() {
        return this.accion;
    }
    
    public void setAccion(Accion accion) {
        this.accion = accion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getPerfils() {
        return this.perfils;
    }
    
    public void setPerfils(Set perfils) {
        this.perfils = perfils;
    }
    public Set getAccions() {
        return this.accions;
    }
    
    public void setAccions(Set accions) {
        this.accions = accions;
    }




}


