package entity;
// Generated May 27, 2015 11:57:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * GuiaRemision generated by hbm2java
 */
public class GuiaRemision  implements java.io.Serializable {


     private Integer id;
     private Cliente cliente;
     private Despacho despacho;
     private Integer estado;
     private Set pallets = new HashSet(0);
     private Set pedidoParcials = new HashSet(0);

    public GuiaRemision() {
    }

	
    public GuiaRemision(Cliente cliente, Despacho despacho) {
        this.cliente = cliente;
        this.despacho = despacho;
    }
    public GuiaRemision(Cliente cliente, Despacho despacho, Integer estado, Set pallets, Set pedidoParcials) {
       this.cliente = cliente;
       this.despacho = despacho;
       this.estado = estado;
       this.pallets = pallets;
       this.pedidoParcials = pedidoParcials;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Despacho getDespacho() {
        return this.despacho;
    }
    
    public void setDespacho(Despacho despacho) {
        this.despacho = despacho;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public Set getPallets() {
        return this.pallets;
    }
    
    public void setPallets(Set pallets) {
        this.pallets = pallets;
    }
    public Set getPedidoParcials() {
        return this.pedidoParcials;
    }
    
    public void setPedidoParcials(Set pedidoParcials) {
        this.pedidoParcials = pedidoParcials;
    }




}


