package entity;
// Generated May 24, 2015 10:16:20 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pallet generated by hbm2java
 */
public class Pallet  implements java.io.Serializable {


     private Integer id;
     private Despacho despacho;
     private Ubicacion ubicacion;
     private String ean128;
     private int idTipoPallet;
     private Date fechaRegistro;
     private Date fechaVencimiento;
     private Set historialMovimientoses = new HashSet(0);
     private Set itemProductos = new HashSet(0);

    public Pallet() {
    }

	
    public Pallet(Despacho despacho, Ubicacion ubicacion, int idTipoPallet) {
        this.despacho = despacho;
        this.ubicacion = ubicacion;
        this.idTipoPallet = idTipoPallet;
    }
    public Pallet(Despacho despacho, Ubicacion ubicacion, String ean128, int idTipoPallet, Date fechaRegistro, Date fechaVencimiento, Set historialMovimientoses, Set itemProductos) {
       this.despacho = despacho;
       this.ubicacion = ubicacion;
       this.ean128 = ean128;
       this.idTipoPallet = idTipoPallet;
       this.fechaRegistro = fechaRegistro;
       this.fechaVencimiento = fechaVencimiento;
       this.historialMovimientoses = historialMovimientoses;
       this.itemProductos = itemProductos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Despacho getDespacho() {
        return this.despacho;
    }
    
    public void setDespacho(Despacho despacho) {
        this.despacho = despacho;
    }
    public Ubicacion getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(Ubicacion ubicacion) {
        this.ubicacion = ubicacion;
    }
    public String getEan128() {
        return this.ean128;
    }
    
    public void setEan128(String ean128) {
        this.ean128 = ean128;
    }
    public int getIdTipoPallet() {
        return this.idTipoPallet;
    }
    
    public void setIdTipoPallet(int idTipoPallet) {
        this.idTipoPallet = idTipoPallet;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaVencimiento() {
        return this.fechaVencimiento;
    }
    
    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }
    public Set getHistorialMovimientoses() {
        return this.historialMovimientoses;
    }
    
    public void setHistorialMovimientoses(Set historialMovimientoses) {
        this.historialMovimientoses = historialMovimientoses;
    }
    public Set getItemProductos() {
        return this.itemProductos;
    }
    
    public void setItemProductos(Set itemProductos) {
        this.itemProductos = itemProductos;
    }




}


