package entity;
// Generated 01-jun-2015 18:57:54 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pallet generated by hbm2java
 */
public class Pallet  implements java.io.Serializable {


     private Integer id;
     private OrdenInternamiento ordenInternamiento;
     private PedidoParcial pedidoParcial;
     private Producto producto;
     private Ubicacion ubicacion;
     private String ean128;
     private Date fechaRegistro;
     private Date fechaVencimiento;
     private Integer estado;
     private Set historialMovimientoses = new HashSet(0);

    public Pallet() {
    }

	
    public Pallet(Producto producto) {
        this.producto = producto;
    }
    public Pallet(OrdenInternamiento ordenInternamiento, PedidoParcial pedidoParcial, Producto producto, Ubicacion ubicacion, String ean128, Date fechaRegistro, Date fechaVencimiento, Integer estado, Set historialMovimientoses) {
       this.ordenInternamiento = ordenInternamiento;
       this.pedidoParcial = pedidoParcial;
       this.producto = producto;
       this.ubicacion = ubicacion;
       this.ean128 = ean128;
       this.fechaRegistro = fechaRegistro;
       this.fechaVencimiento = fechaVencimiento;
       this.estado = estado;
       this.historialMovimientoses = historialMovimientoses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public OrdenInternamiento getOrdenInternamiento() {
        return this.ordenInternamiento;
    }
    
    public void setOrdenInternamiento(OrdenInternamiento ordenInternamiento) {
        this.ordenInternamiento = ordenInternamiento;
    }
    public PedidoParcial getPedidoParcial() {
        return this.pedidoParcial;
    }
    
    public void setPedidoParcial(PedidoParcial pedidoParcial) {
        this.pedidoParcial = pedidoParcial;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Ubicacion getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(Ubicacion ubicacion) {
        this.ubicacion = ubicacion;
    }
    public String getEan128() {
        return this.ean128;
    }
    
    public void setEan128(String ean128) {
        this.ean128 = ean128;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaVencimiento() {
        return this.fechaVencimiento;
    }
    
    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public Set getHistorialMovimientoses() {
        return this.historialMovimientoses;
    }
    
    public void setHistorialMovimientoses(Set historialMovimientoses) {
        this.historialMovimientoses = historialMovimientoses;
    }




}


