package entity;
// Generated May 26, 2015 4:12:25 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PedidoParcial generated by hbm2java
 */
public class PedidoParcial  implements java.io.Serializable {


     private Integer id;
     private GuiaRemision guiaRemision;
     private Pedido pedido;
     private Integer estado;
     private Set itemProductos = new HashSet(0);

    public PedidoParcial() {
    }

	
    public PedidoParcial(Pedido pedido) {
        this.pedido = pedido;
    }
    public PedidoParcial(GuiaRemision guiaRemision, Pedido pedido, Integer estado, Set itemProductos) {
       this.guiaRemision = guiaRemision;
       this.pedido = pedido;
       this.estado = estado;
       this.itemProductos = itemProductos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public GuiaRemision getGuiaRemision() {
        return this.guiaRemision;
    }
    
    public void setGuiaRemision(GuiaRemision guiaRemision) {
        this.guiaRemision = guiaRemision;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public Set getItemProductos() {
        return this.itemProductos;
    }
    
    public void setItemProductos(Set itemProductos) {
        this.itemProductos = itemProductos;
    }




}


