package entity;
// Generated May 25, 2015 12:04:54 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer id;
     private Condicion condicion;
     private String nombre;
     private String descripcion;
     private Integer stockTotal;
     private Set itemProductos = new HashSet(0);
     private Set kardexes = new HashSet(0);

    public Producto() {
    }

	
    public Producto(Condicion condicion) {
        this.condicion = condicion;
    }
    public Producto(Condicion condicion, String nombre, String descripcion, Integer stockTotal, Set itemProductos, Set kardexes) {
       this.condicion = condicion;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.stockTotal = stockTotal;
       this.itemProductos = itemProductos;
       this.kardexes = kardexes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Condicion getCondicion() {
        return this.condicion;
    }
    
    public void setCondicion(Condicion condicion) {
        this.condicion = condicion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getStockTotal() {
        return this.stockTotal;
    }
    
    public void setStockTotal(Integer stockTotal) {
        this.stockTotal = stockTotal;
    }
    public Set getItemProductos() {
        return this.itemProductos;
    }
    
    public void setItemProductos(Set itemProductos) {
        this.itemProductos = itemProductos;
    }
    public Set getKardexes() {
        return this.kardexes;
    }
    
    public void setKardexes(Set kardexes) {
        this.kardexes = kardexes;
    }




}


