package entity;
// Generated 13/06/2015 10:34:15 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Sesion generated by hbm2java
 */
public class Sesion  implements java.io.Serializable {


     private Integer id;
     private Usuario usuario;
     private Date inicioSesion;
     private Date finSesion;
     private String ip;
     private String mac;

    public Sesion() {
    }

    public Sesion(Usuario usuario, Date inicioSesion, Date finSesion, String ip, String mac) {
       this.usuario = usuario;
       this.inicioSesion = inicioSesion;
       this.finSesion = finSesion;
       this.ip = ip;
       this.mac = mac;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getInicioSesion() {
        return this.inicioSesion;
    }
    
    public void setInicioSesion(Date inicioSesion) {
        this.inicioSesion = inicioSesion;
    }
    public Date getFinSesion() {
        return this.finSesion;
    }
    
    public void setFinSesion(Date finSesion) {
        this.finSesion = finSesion;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public String getMac() {
        return this.mac;
    }
    
    public void setMac(String mac) {
        this.mac = mac;
    }




}


