package entity;
// Generated 06/06/2015 09:17:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoProducto generated by hbm2java
 */
public class TipoProducto  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String descripcion;
     private Set productos = new HashSet(0);

    public TipoProducto() {
    }

    public TipoProducto(String nombre, String descripcion, Set productos) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.productos = productos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


