package entity;
// Generated 21-May-2015 00:05:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ubicacion generated by hbm2java
 */
public class Ubicacion  implements java.io.Serializable {


     private int id;
     private Rack rack;
     private Integer fila;
     private Integer columna;
     private String lado;
     private Integer ocupado;
     private Set pallets = new HashSet(0);

    public Ubicacion() {
    }

	
    public Ubicacion(int id, Rack rack) {
        this.id = id;
        this.rack = rack;
    }
    public Ubicacion(int id, Rack rack, Integer fila, Integer columna, String lado, Integer ocupado, Set pallets) {
       this.id = id;
       this.rack = rack;
       this.fila = fila;
       this.columna = columna;
       this.lado = lado;
       this.ocupado = ocupado;
       this.pallets = pallets;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Rack getRack() {
        return this.rack;
    }
    
    public void setRack(Rack rack) {
        this.rack = rack;
    }
    public Integer getFila() {
        return this.fila;
    }
    
    public void setFila(Integer fila) {
        this.fila = fila;
    }
    public Integer getColumna() {
        return this.columna;
    }
    
    public void setColumna(Integer columna) {
        this.columna = columna;
    }
    public String getLado() {
        return this.lado;
    }
    
    public void setLado(String lado) {
        this.lado = lado;
    }
    public Integer getOcupado() {
        return this.ocupado;
    }
    
    public void setOcupado(Integer ocupado) {
        this.ocupado = ocupado;
    }
    public Set getPallets() {
        return this.pallets;
    }
    
    public void setPallets(Set pallets) {
        this.pallets = pallets;
    }




}


