/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.client;

import application.local.LocalApplication;
import static client.client.LocalsView.localsView;
import entity.Cliente;
import entity.Local;
import java.util.Locale;
import javax.swing.JOptionPane;
import util.EntityState;
import util.EntityState.Locals;
import util.InstanceFactory;
import util.Strings;

/**
 *
 * @author prote_000
 */
public class NewLocalView extends javax.swing.JDialog {
    Cliente client = null;
    LocalApplication localApplication=InstanceFactory.Instance.getInstance("localApplication", LocalApplication.class);
    /**
     * Creates new form NewLocalView
     */
    public NewLocalView(java.awt.Frame parent, boolean modal, Cliente client) {
        super(parent, modal);
        initComponents();
        this.client = client;
    }

    public void clearFields(){
        txtName.setText("");
        txtLat.setText("");
        txtLong.setText("");
        txtDescripcion.setText("");
        txtDireccion.setText("");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtLat = new javax.swing.JTextField();
        txtLong = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Local");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Latitud");

        jLabel2.setText("Longitud");

        jLabel3.setText("Nombre");

        jLabel4.setText("Descripción");

        jLabel5.setText("Dirección");

        btnSave.setText("Guardar");
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSaveMousePressed(evt);
            }
        });

        btnCancel.setText("Cancelar");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCancelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName)
                            .addComponent(txtLat)
                            .addComponent(txtLong)
                            .addComponent(txtDescripcion)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMousePressed
        this.dispose();
        //localsView.fillLocalsTable();
    }//GEN-LAST:event_btnCancelMousePressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        localsView.fillLocalsTable();
    }//GEN-LAST:event_formWindowClosed

    public boolean isDouble( String str ){
        try{
            Double.parseDouble( str );
            return true;
        }catch( Exception e ){
            return false;
        }
    }
    
    private void btnSaveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMousePressed
        String error_message = "Errores:\n\n";
        JOptionPane.setDefaultLocale(new Locale("es", "ES"));
        boolean hasErrors = false;
        if(txtLat.getText().isEmpty()){
            error_message += Strings.ERROR_LATITUDE_REQUIRED+"\n";
            hasErrors = true;
        }else if(!isDouble(txtLat.getText())){
            error_message += Strings.ERROR_LATITUDE_NOT_FLOAT+"\n";
            hasErrors = true;
        }
        if(txtLong.getText().isEmpty()){
            error_message += Strings.ERROR_LONGITUDE_REQUIRED+"\n";
            hasErrors = true;
        }else if(!isDouble(txtLong.getText())){
            error_message += Strings.ERROR_LONGITUDE_NOT_FLOAT+"\n";
            hasErrors = true;
        }
        if(txtName.getText().length()<1){
            error_message += Strings.ERROR_NAME_LESS_2+"\n";
            hasErrors = true;
        }
        if(txtDireccion.getText().isEmpty()){
            error_message += Strings.ERROR_ADDRESS_REQUIRED+"\n";
            hasErrors = true;
        }
        
        if(hasErrors){
            JOptionPane.showMessageDialog(this, error_message,Strings.ERROR_NEW_LOCAL_TITLE,JOptionPane.ERROR_MESSAGE);
        }else{
            Local local = new Local();
            local.setCliente(client);
            local.setDireccion(txtDireccion.getText());
            local.setLatitud(Double.parseDouble(txtLat.getText()));
            local.setLongitud(Double.parseDouble(txtLong.getText()));
            if(!txtDescripcion.getText().isEmpty()){
                local.setDescripcion(txtDescripcion.getText());
            }
            local.setEstado(Locals.ACTIVO.ordinal());
            local.setNombre(txtName.getText());
            localApplication.insert(local);
            JOptionPane.showMessageDialog(this, Strings.MESSAGE_NEW_LOCAL_CREATED,Strings.MESSAGE_NEW_LOCAL_TITLE,JOptionPane.INFORMATION_MESSAGE);
            clearFields();
        }
    }//GEN-LAST:event_btnSaveMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtLat;
    private javax.swing.JTextField txtLong;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
